# sulix gitlab CI repo checker.
image: debian:testing

index:
  stage: build
  script:
    - apt update
    - apt full-upgrade -y
    - apt install meson gcc valac git --no-install-recommends -y
    - apt install libarchive-dev libreadline-dev libcurl4-openssl-dev libbrotli-dev --no-install-recommends -y
    - git clone https://gitlab.com/sulix/devel/sources/ymp
    - cd ymp
    - meson build -Dlibbrotli=false --prefix=/usr
    - ninja -C build install
    - cd ../ && rm -rf ymp
    - bash update.sh
 