# sulix gitlab CI repo checker.
image: debian:testing

index:
  artifacts:
    paths:
      - output

  stage: build
  script:
    - apt update &>/dev/null
    - apt full-upgrade -y  &>/dev/null
    - apt install meson gcc valac git --no-install-recommends -y  &>/dev/null
    - apt install libarchive-dev libreadline-dev libcurl4-openssl-dev libbrotli-dev ca-certificates --no-install-recommends -y  &>/dev/null
    - git clone https://gitlab.com/sulix/devel/sources/ymp.git ymp && cd ymp  &>/dev/null
    - meson build -Dlibbrotli=false --prefix=/usr --libdir=/lib  &>/dev/null
    - ninja -C build install  &>/dev/null
    - ldconfig  &>/dev/null
    - cd ../ && rm -rf ymp  &>/dev/null
    - bash update.sh
 
release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Index release"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
